disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try
  - identifier_name
  - type_body_length
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - large_tuple
  - function_parameter_count
  - type_name
  - shorthand_operator
